server/server/urls.py
from django.contrib import admin
from django.urls import path

import my_site.views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', my_site.views.index_page),
    path("calc/", my_site.views.calc_page)
]

server/my_site/models.py
from django.db import models


class CalcHistory(models.Model):
    first_number = models.IntegerField()
    second_number = models.IntegerField()
    result_number = models.IntegerField()
    date = models.DateTimeField()

server/my_site/forms.py
from django import forms


class CalcForm(forms.Form):
    first_number = forms.IntegerField(label="Первое число", min_value=-100, max_value=100,
                                      widget=forms.NumberInput(attrs={"class": "form-control"}))
    second_number = forms.IntegerField(label="Второе число", min_value=-100, max_value=100,
                                       widget=forms.NumberInput(attrs={"class": "form-control"}))

server/my_site/views.py
import datetime

from django.http import HttpRequest, HttpResponse
from django.shortcuts import render

from my_site.forms import CalcForm
from my_site.models import CalcHistory


def get_default_menu() -> tuple:
    return (
        {"link": '/', "text": "Главная"},
        {"link": "/calc/", "text": "Калькулятор"}
    )


def index_page(request: HttpRequest) -> HttpResponse:
    context = {"page_name": "Главная", "menu": get_default_menu(), "current_link": '/'}

    return render(request, "index.html", context)


def calc_page(request: HttpRequest) -> HttpResponse:
    context = {"page_name": "Калькулятор", "menu": get_default_menu(), "current_link": "/calc/"}

    if request.method == "POST":
        calc_form_get = CalcForm(request.POST)

        # Тут по хорошему надо проверить форму на валидность -- но мы это опустим (если на предыдущем занятии)

        first_number = calc_form_get.data["first_number"]
        second_number = calc_form_get.data["second_number"]

        result_number = int(first_number) + int(second_number)

        CalcHistory(first_number=first_number, second_number=second_number, result_number=result_number,
                    date=datetime.datetime.now()).save()

        context["calc_form"] = calc_form_get
    else:
        context["calc_form"] = CalcForm()

    context["calc_history"] = CalcHistory.objects.all()

    return render(request, "calc.html", context)

server/my_site/templates/base_htmls/base.html
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL"
            crossorigin="anonymous"></script>
    <!--    Каждый раз мы будем передавать название страницы в context'е-->
    <title>{{ page_name }}</title>
</head>
<body>
<!--Нам нужно определить те места, куда мы будем вставлять кусочки кода-->
<header>
    {% include "base_htmls/menu.html" %}
</header>
<main>
    <!--    таким образом я определяю место, куда можно вставить код-->
    <!--    Имя блока может быть любым-->
    {% block main %}
    {% endblock %}
</main>
<footer>
    {% block footer %}
    <p>Если вы видите эту надпись -- то вы не переопределили блок подвала!</p>
    {% endblock %}
</footer>
</body>
</html>

server/my_site/templates/base_htmls/menu.html
<nav class="navbar navbar-expand-lg bg-body-tertiary">
    <div class="container-fluid">
        <a class="navbar-brand" href="{{ current_link }}">{{ page_name }}</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup"
                aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
            <div class="navbar-nav">
                {% for menu_item in menu %}
                {% if menu_item.text != page_name %}
                <a class="nav-link" href="{{ menu_item.link }}">{{ menu_item.text }}</a>
                {% endif %}
                {% endfor %}
            </div>
        </div>
    </div>
</nav>

server/my_site/templates/calc.html
{% extends "base_htmls/base.html" %}

{% block main %}
<div class="row">
    <div class="col">
        <section>
            <div class="container">
                <div class="card mb-3">
                    <div class="card-header">Форма для калькулятора</div>
                    <div class="card-body">
                        <form action="/calc/" method="post">
                            {% csrf_token %}
                            <div class="mb-3">
                                <label for="id_first_number"
                                       class="form-label">{{ calc_form.first_number.label }}</label>
                                {{ calc_form.first_number }}
                            </div>
                            <div class="mb-3">
                                <label for="id_second_number"
                                       class="form-label">{{ calc_form.second_number.label }}</label>
                                {{ calc_form.second_number }}
                            </div>
                            <button type="submit" class="btn btn-primary">Отправить на сервер</button>
                        </form>
                    </div>
                </div>
            </div>
        </section>
    </div>
    <div class="col">
        <section>
            <div class="container">
                <div class="card mb-3">
                    <div class="card-header">История для калькулятора</div>
                    <div class="card-body">
                        <ol class="list-group">
                            {% for item_history in calc_history %}
                            <li class="list-group-item">
                                Операция за дату {{ item_history.date }}
                                <ol>
                                    <li>Первое число -- {{ item_history.first_number }}</li>
                                    <li>Второе число -- {{ item_history.second_number }}</li>
                                    <li>Результат -- {{ item_history.result_number }}</li>
                                </ol>
                            </li>
                            {% endfor %}
                        </ol>
                    </div>
                </div>
            </div>
        </section>
    </div>
</div>
{% endblock %}

server/my_site/templates/index.html
<!--1. Нужно отнаследовать html-файл-->
{% extends "base_htmls/base.html" %}

<!--2. А теперь просто выбирайте доступные для редактирования блоки и редактируйте их!-->
{% block main %}
<!--<h2>Я сделал сайт!</h2>-->
<div class="container">
    <div class="card">
        <div class="card-header">
            Великая цитата
        </div>
        <div class="card-body">
            <blockquote class="blockquote mb-0">
                <p>Зачем нам сейчас долго тратить время на CSS, если Владислав Алексанов для нас уже всё подготовил.</p>
                <footer class="blockquote-footer">Ваш преподаватель, <cite title="АНС">АНС</cite></footer>
            </blockquote>
        </div>
    </div>
</div>
{% endblock %}